spring.application.name=turmaa

#Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/turmaa?useSSL=false&serverTimeZone=UTC
#jdbc:postgres
#//localhost:5432 Servidor está hospedado na própria máquina
#//Nomedobancodedados: turmaa

#Nome do Usuário administrador do postgreSQL:
spring.datasource.username=postgres

#Senha do Usuário do PostgreSQL:
spring.datasource.password=postgres

#Define a classe do Driver JDBC usada pelo Spring para
#se comunicar com o PostgreSQL

spring.datasource.driver-class-name=org.postgresql.Driver

#Habilita a geração automática de DDL (Data Definition Language)
#pelo Spring JPA

spring.jpa.generate-ddl=true

#Estratégia de gerenciamento de tabelas Hibernate:
#'update' -> cria novas tabelas e atualiza coluns de entidades @Entity
#sem apagar os dados existentes

spring.jpa.hibernate.ddl-auto=update

#Exibe os comandos SQL gerados no console (ótimo para conferir
#a criação de tabelas e inserts).

spring.jpa.show-sql=true

#Formata o SQL exibido no console para facilitar a leitura
#com quebras de linha e recuos)
spring.jpa.properties.hibernate.format_sql=true

#Esquema padrão
spring.jpa.properties.hibernate.default_schema=public

#